import { lazy, Suspense } from "react";
import Hero from "../components/Home/Hero";
import Projects from "../components/Home/Projects";
import { projectItem, miniProjectItem, Theme } from "../utils/constants";

// Below-the-fold sections are code-split — Hero and Projects (the
// first thing anyone sees) load eagerly; everything the person only
// reaches by scrolling loads in parallel right after, cutting initial
// JS parse/execute time without the person ever noticing a loading
// state in practice.
const MoreProjects = lazy(() => import("../components/Home/MoreProjects"));
const DeveloperTools = lazy(() => import("../components/Home/DeveloperTools"));
const Skills = lazy(() => import("../components/Home/Skills"));
const About = lazy(() => import("../components/Home/About"));
const Services = lazy(() => import("../components/Home/Services"));
const Contact = lazy(() => import("../components/Home/Contact"));

// Minimal-height placeholder — prevents a jarring layout jump while a
// chunk loads, without needing to hand-tune a skeleton per section.
const SectionFallback = () => <div className="min-h-[50vh]" />;

/* ===================== FLAGSHIP PROJECTS ===================== */
/* Verified live at github.com/Zephyrex21 — descriptions, tech, and
   links are pulled directly from each repo. */

const flagshipProjects: projectItem[] = [
  {
    title: "Agentic RAG Assistant",
    description:
      "Agentic RAG assistant with hybrid retrieval and LLM reranking — every answer traces back to its exact source with verifiable citations.",
    tech: ["Node.js", "Express", "React", "Gemini", "Pinecone", "Supabase"],
    link: "https://github.com/Zephyrex21/agentic-rag-assistant",
    codeLink: "https://github.com/Zephyrex21/agentic-rag-assistant",
    image: { dark: "/screenshots/rag-assistant-dark.webp", light: "/screenshots/rag-assistant-light.webp" },
    gradientFrom: "#303030",
    gradientTo: "#121212",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "AI Data Analyst Agent",
    description:
      "Ask questions about a CSV in plain English — verified SQL/Python generated by an LLM, executed entirely in the browser via DuckDB-WASM and Pyodide. Zero backend, zero cost.",
    tech: ["TypeScript", "DuckDB-WASM", "Pyodide", "LLM"],
    link: "https://ai-data-analyst-agent-one.vercel.app",
    codeLink: "https://github.com/Zephyrex21/ai-data-analyst-agent",
    image: { dark: "/screenshots/ai-data-analyst-dark.webp", light: "/screenshots/ai-data-analyst-light.webp" },
    gradientFrom: "#272727",
    gradientTo: "#101010",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Cryptex File Sharing",
    description:
      "A secure, token-based file sharing platform built with the MERN stack and Supabase Storage, supporting folders and shareable links.",
    tech: ["MongoDB", "Express", "Node.js", "Supabase"],
    link: "https://cryptex-file-sharing.onrender.com",
    codeLink: "https://github.com/Zephyrex21/cryptex-file-sharing",
    image: { dark: "/screenshots/cryptex-dark.webp", light: "/screenshots/cryptex-light.webp" },
    gradientFrom: "#242424",
    gradientTo: "#0c0c0c",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Urban Heat Mitigation",
    description:
      "AI/ML system optimizing urban heat mitigation and cooling strategies across 20 cities — submitted to ISRO's Bharatiya Antariksh Hackathon (BAH) 2026, using XGBoost and SHAP for explainability.",
    tech: ["Python", "XGBoost", "SHAP", "React"],
    link: "https://urban-heat-mitigation-mu.vercel.app",
    codeLink: "https://github.com/Zephyrex21/urban-heat-mitigation",
    image: { dark: "/screenshots/urban-heat-dark.webp", light: "/screenshots/urban-heat-light.webp" },
    gradientFrom: "#262626",
    gradientTo: "#0d0d0d",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Mind Forge",
    description:
      "An AI-powered mental wellness platform that helps users build healthier habits through intelligent conversations, guided journaling, mood tracking, and personalized daily check-ins.",
    tech: ["React", "Node.js", "MongoDB", "Gemini"],
    link: "https://mind-forge-iota-ashy.vercel.app",
    codeLink: "https://github.com/Zephyrex21/mind-forge",
    image: { dark: "/screenshots/mind-forge-dark.webp", light: "/screenshots/mind-forge-light.webp" },
    gradientFrom: "#2b2b2b",
    gradientTo: "#111111",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "ChatSite AI",
    description:
      "Paste any URL and chat with it — every answer is checked against the page's actual content instead of filled in from a guess. Built portfolio-grade with full CI/CD, testing, and SSRF-hardened scraping so it can't be pointed at internal infrastructure.",
    tech: ["Next.js", "Prisma", "PostgreSQL", "Gemini"],
    link: "https://chatsite-ai-indol.vercel.app",
    codeLink: "https://github.com/Zephyrex21/chatsite-ai",
    gradientFrom: "#2d2d2d",
    gradientTo: "#131313",
    status: "completed",
    projectType: "personal",
  },
];

/* ===================== MORE PROJECTS ===================== */

const moreProjects: miniProjectItem[] = [
  {
    title: "GitHub Contribution Radar",
    description:
      "AI-powered GitHub contribution discovery platform — GitHub OAuth, a Gemini-based issue summarizer, and CSV export, wrapped in a command palette.",
    stack: "React · TanStack Query · Gemini",
    link: "https://github-contribution-radar.vercel.app",
    codeLink: "https://github.com/Zephyrex21/github-contribution-radar",
  },
  {
    title: "Automata Lab",
    description:
      "Interactive NFA/DFA simulator and model-conversion visualizer for TAFL concepts.",
    stack: "HTML · JS Canvas",
    link: "https://automata-lab.netlify.app",
    codeLink: "https://github.com/Zephyrex21/automata-visualizer",
  },
  {
    title: "CFG Studio",
    description: "Context-free grammar visualizer with Earley parsing.",
    stack: "HTML · JavaScript",
    link: "https://cfg-studio.netlify.app",
    codeLink: "https://github.com/Zephyrex21/cfg-studio",
  },
  {
    title: "Roséa",
    description:
      "Interactive luxury product film — a 240-frame scroll-scrubbed canvas hero driven by GSAP ScrollTrigger.",
    stack: "React · TypeScript · GSAP · MongoDB",
    link: "https://rosea-product-landing.vercel.app",
    codeLink: "https://github.com/Zephyrex21/rosea-product-landing",
  },
  {
    title: "CSP Playground",
    description:
      "Backtracking search visualizer for Sudoku, N-Queens, and graph coloring.",
    stack: "HTML · JavaScript",
    link: "https://github.com/Zephyrex21/csp-playground",
    codeLink: "https://github.com/Zephyrex21/csp-playground",
  },
];

const Home: React.FC<{ theme: Theme }> = ({ theme }) => {
  return (
    <>
      <Hero />
      <Projects projects={flagshipProjects} theme={theme} />
      <Suspense fallback={<SectionFallback />}>
        <MoreProjects projects={moreProjects} />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <DeveloperTools />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <Skills />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <About />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <Services />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <Contact />
      </Suspense>
    </>
  );
};

export default Home;
