import { lazy, Suspense } from "react";
import Hero from "../components/Home/Hero";
import Projects from "../components/Home/Projects";
import { projectItem, miniProjectItem, Theme } from "../utils/constants";

// Below-the-fold sections are code-split — Hero and Projects (the
// first thing anyone sees) load eagerly; everything the person only
// reaches by scrolling loads in parallel right after, cutting initial
// JS parse/execute time without the person ever noticing a loading
// state in practice.
const MoreProjects = lazy(() => import("../components/Home/MoreProjects"));
const DeveloperTools = lazy(() => import("../components/Home/DeveloperTools"));
const Skills = lazy(() => import("../components/Home/Skills"));
const About = lazy(() => import("../components/Home/About"));
const Services = lazy(() => import("../components/Home/Services"));
const Contact = lazy(() => import("../components/Home/Contact"));

// Minimal-height placeholder — prevents a jarring layout jump while a
// chunk loads, without needing to hand-tune a skeleton per section.
const SectionFallback = () => <div className="min-h-[50vh]" />;

/* ===================== FLAGSHIP PROJECTS ===================== */
/* Verified live at github.com/Zephyrex21 — descriptions, tech, and
   links are pulled directly from each repo. */

const flagshipProjects: projectItem[] = [
  {
    title: "Kaira AI Agent",
    description:
      "A multimodal AI agent built with React and Python — local wake-word detection, system registry management, autonomous coding tools, and persistent memory across sessions.",
    tech: ["React", "Python", "TypeScript", "LLM Agents"],
    link: "https://github.com/Zephyrex21/kaira-ai-agent",
    codeLink: "https://github.com/Zephyrex21/kaira-ai-agent",
    gradientFrom: "#2a2a2a",
    gradientTo: "#0f0f0f",
    status: "in-progress",
    projectType: "personal",
  },
  {
    title: "Agentic RAG Assistant",
    description:
      "Agentic RAG assistant with hybrid retrieval and LLM reranking — every answer traces back to its exact source with verifiable citations.",
    tech: ["Node.js", "Express", "React", "Gemini", "Pinecone", "Supabase"],
    link: "https://github.com/Zephyrex21/agentic-rag-assistant",
    codeLink: "https://github.com/Zephyrex21/agentic-rag-assistant",
    gradientFrom: "#303030",
    gradientTo: "#121212",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "AI Data Analyst Agent",
    description:
      "Ask questions about a CSV in plain English — verified SQL/Python generated by an LLM, executed entirely in the browser via DuckDB-WASM and Pyodide. Zero backend, zero cost.",
    tech: ["TypeScript", "DuckDB-WASM", "Pyodide", "LLM"],
    link: "https://ai-data-analyst-agent-one.vercel.app",
    codeLink: "https://github.com/Zephyrex21/ai-data-analyst-agent",
    gradientFrom: "#272727",
    gradientTo: "#101010",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Vision Interpretability Studio",
    description:
      "In-browser tool for seeing inside a vision model — live Grad-CAM, feature visualization, and a ResNet-18 trained from scratch, running entirely client-side via ONNX Runtime Web.",
    tech: ["TypeScript", "ONNX Runtime Web", "ResNet-18", "Grad-CAM"],
    link: "https://vision-interpretability-studio.vercel.app",
    codeLink: "https://github.com/Zephyrex21/vision-interpretability-studio",
    gradientFrom: "#2d2d2d",
    gradientTo: "#131313",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Urban Heat Mitigation",
    description:
      "AI/ML system optimizing urban heat mitigation and cooling strategies across 20 cities — submitted to ISRO's Bharatiya Antariksh Hackathon (BAH) 2026, using XGBoost and SHAP for explainability.",
    tech: ["Python", "XGBoost", "SHAP", "React"],
    link: "https://urban-heat-mitigation-mu.vercel.app",
    codeLink: "https://github.com/Zephyrex21/urban-heat-mitigation",
    image: { dark: "/screenshots/urban-heat-dark.webp", light: "/screenshots/urban-heat-light.webp" },
    gradientFrom: "#262626",
    gradientTo: "#0d0d0d",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Mind Forge",
    description:
      "An AI-powered mental wellness platform that helps users build healthier habits through intelligent conversations, guided journaling, mood tracking, and personalized daily check-ins.",
    tech: ["React", "Node.js", "MongoDB", "Gemini"],
    link: "https://mind-forge-iota-ashy.vercel.app",
    codeLink: "https://github.com/Zephyrex21/mind-forge",
    image: { dark: "/screenshots/mind-forge-dark.webp", light: "/screenshots/mind-forge-light.webp" },
    gradientFrom: "#2b2b2b",
    gradientTo: "#111111",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "GitHub Contribution Radar",
    description:
      "AI-powered GitHub contribution discovery and open-source tracking platform — GitHub OAuth, TanStack Query, a Gemini-based issue summarizer, CSV export, and a command palette.",
    tech: ["React", "TanStack Query", "GitHub OAuth", "Gemini"],
    link: "https://github-contribution-radar.vercel.app",
    codeLink: "https://github.com/Zephyrex21/github-contribution-radar",
    image: { dark: "/screenshots/upstream-dark.webp", light: "/screenshots/upstream-light.webp" },
    gradientFrom: "#292929",
    gradientTo: "#0f0f0f",
    status: "completed",
    projectType: "personal",
  },
  {
    title: "Cryptex File Sharing",
    description:
      "A secure, token-based file sharing platform built with the MERN stack and Supabase Storage, supporting folders and shareable links.",
    tech: ["MongoDB", "Express", "Node.js", "Supabase"],
    link: "https://cryptex-file-sharing.onrender.com",
    codeLink: "https://github.com/Zephyrex21/cryptex-file-sharing",
    image: { dark: "/screenshots/cryptex-dark.webp", light: "/screenshots/cryptex-light.webp" },
    gradientFrom: "#242424",
    gradientTo: "#0c0c0c",
    status: "completed",
    projectType: "personal",
  },
];

/* ===================== MORE PROJECTS ===================== */

const moreProjects: miniProjectItem[] = [
  {
    title: "NeighborNet",
    description:
      "Location-based community platform for discovering and sharing local resources in real time.",
    stack: "TypeScript · Firebase · Leaflet",
    link: "https://neighbornet-ten.vercel.app",
    codeLink: "https://github.com/Zephyrex21/neighbornet",
  },
  {
    title: "Concourse AI",
    description:
      "Multilingual GenAI assistant for FIFA World Cup 2026 stadium operations — built for PromptWars Challenge 4.",
    stack: "GenAI · Multilingual",
    link: "https://concourse-ai-one.vercel.app",
    codeLink: "https://github.com/Zephyrex21/concourse-ai",
  },
  {
    title: "API Guardian",
    description:
      "GitHub App that catches breaking OpenAPI changes in pull requests via semantic contract analysis.",
    stack: "Node.js · GitHub App",
    link: "https://github.com/Zephyrex21/api-guardian-sandbox",
    codeLink: "https://github.com/Zephyrex21/api-guardian-sandbox",
  },
  {
    title: "ChatSite AI",
    description:
      "Paste a URL, get a grounded AI conversation about its actual content — SSRF-hardened scraping.",
    stack: "Next.js 16 · Prisma 7 · Gemini",
    link: "https://github.com/Zephyrex21/chatsite-ai",
    codeLink: "https://github.com/Zephyrex21/chatsite-ai",
  },
  {
    title: "Automata Lab",
    description:
      "Interactive NFA/DFA simulator and model-conversion visualizer for TAFL concepts.",
    stack: "HTML · JS Canvas",
    link: "https://automata-lab.netlify.app",
    codeLink: "https://github.com/Zephyrex21/automata-visualizer",
  },
  {
    title: "Red-Blackify",
    description:
      "Red-black tree visualizer showing rotations and recoloring during insertion, live.",
    stack: "JavaScript",
    link: "https://rbt-visualizer.netlify.app",
    codeLink: "https://github.com/Zephyrex21/rbt-visualizer",
  },
  {
    title: "CFG Studio",
    description: "Context-free grammar visualizer with Earley parsing.",
    stack: "HTML · JavaScript",
    link: "https://cfg-studio.netlify.app",
    codeLink: "https://github.com/Zephyrex21/cfg-studio",
  },
  {
    title: "Task Scheduler Visualizer",
    description:
      "CPU scheduling visualizer for FCFS, SJF, Round Robin, and Priority algorithms.",
    stack: "HTML · CSS · JS",
    link: "https://process-visualizer.netlify.app",
    codeLink: "https://github.com/Zephyrex21/task-scheduler-visualizer",
  },
  {
    title: "CSP Playground",
    description:
      "Backtracking search visualizer for Sudoku, N-Queens, and graph coloring.",
    stack: "HTML · JavaScript",
    link: "https://github.com/Zephyrex21/csp-playground",
    codeLink: "https://github.com/Zephyrex21/csp-playground",
  },
];

const Home: React.FC<{ theme: Theme }> = ({ theme }) => {
  return (
    <>
      <Hero />
      <Projects projects={flagshipProjects} theme={theme} />
      <Suspense fallback={<SectionFallback />}>
        <MoreProjects projects={moreProjects} />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <DeveloperTools />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <Skills />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <About />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <Services />
      </Suspense>
      <Suspense fallback={<SectionFallback />}>
        <Contact />
      </Suspense>
    </>
  );
};

export default Home;
